<?php

namespace ContainerJD5ucGT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IVkeohWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IVkeohW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IVkeohW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bet' => ['privates', '.errored..service_locator.IVkeohW.App\\Entity\\Bets', NULL, 'Cannot autowire service ".service_locator.IVkeohW": it references class "App\\Entity\\Bets" but no such service exists.'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'bet' => 'App\\Entity\\Bets',
            'serializer' => '?',
        ]);
    }
}
