<?php

namespace ContainerJD5ucGT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTesterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\Tester' shared autowired service.
     *
     * @return \App\Validator\Tester
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Validator/Tester.php';

        return $container->privates['App\\Validator\\Tester'] = new \App\Validator\Tester();
    }
}
