<?php

namespace Container1hjegBg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cdl7IKXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cdl7IKX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cdl7IKX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'repository' => ['privates', 'App\\Repository\\BetsRepository', 'getBetsRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'cache' => '?',
            'repository' => 'App\\Repository\\BetsRepository',
            'serializer' => '?',
        ]);
    }
}
