<?php

namespace Container1hjegBg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZfQts79Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZfQts79' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZfQts79'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bet' => ['privates', '.errored..service_locator.ZfQts79.App\\Entity\\Bets', NULL, 'Cannot autowire service ".service_locator.ZfQts79": it references class "App\\Entity\\Bets" but no such service exists.'],
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'bet' => 'App\\Entity\\Bets',
            'cache' => '?',
            'manager' => '?',
            'serializer' => '?',
        ]);
    }
}
