<?php

namespace Container1hjegBg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8WEWLxf.App\Entity\Bets' shared service.
     *
     * @return \App\Entity\Bets
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8WEWLxf": it references class "App\\Entity\\Bets" but no such service exists.');
    }
}
