<?php

namespace Container1hjegBg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatchsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.e0O5x1D.App\Entity\Matchs' shared service.
     *
     * @return \App\Entity\Matchs
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.e0O5x1D": it references class "App\\Entity\\Matchs" but no such service exists.');
    }
}
