<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1hjegBg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1hjegBg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1hjegBg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1hjegBg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1hjegBg\App_KernelDevDebugContainer([
    'container.build_hash' => '1hjegBg',
    'container.build_id' => '3e79ca07',
    'container.build_time' => 1709741348,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1hjegBg');
